---
title: "Weight of Fish"
author: "Hayden Wood"
date: "Spring 2024"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

```{r}
install.packages("MASS")  # Install the MASS package
library(MASS)             # Load the MASS package
```

```{r}
library(MASS)
```


## Read in fisy data
```{r}
fishALL = read_csv('Fish.csv')
```


# Predicting Fish Weight


## Perch

```{r}
perchFish = filter(fishALL, Species=='Perch') 
perchModel = lm(Weight~Length1+Length2+Length3+Height+Width, data= perchFish)
summary.lm(perchModel)
```


### Best Models
We find best models for for all three species

```{r}
best_models_perch <- step(perchModel)
```

```{r}
summary.lm(best_models_perch)
```



### Best Two regressor model


```{r}
best_two_regressor_perch <- stepAIC(perchModel, direction = "both", trace = FALSE, k = 2)
```

```{r}
summary.lm(best_two_regressor_perch)
```


## Pike
```{r}
pikeFish = filter(fishALL, Species=='Pike') 
```

```{r}
pikeModel = lm(Weight~Length1+Length2+Length3+Height+Width, data= pikeFish)
```

```{r}
summary.lm(pikeModel)
```


### Best Models



### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements